### ISSUE TITLE
Footer: Font weight of the widget title

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/tb_blog#10]
Description:
Font weight of the widget title on the staging is 600 which makes them look bold whereas on the reference site it is 400px

Screenshot:
From staging
![image](https://user-images.githubusercontent.com/75774252/146356027-6068ada1-f825-4525-a5aa-bc83e2ff46aa.png)

From ref:
![image](https://user-images.githubusercontent.com/75774252/146355622-663e855d-19e4-453a-903d-89834c384a16.png)

**Comment by EktaNaik** [comment]
Fixed.
