### ISSUE TITLE
Homepage - Banner: there should be some space between the icon and the next alphabet

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/tb_blog#11]
Description:
There is little/no space between the icon and the next alphabet

Screenshot:
From the staging
![image](https://user-images.githubusercontent.com/75774252/146358581-d1d2106e-ef00-4fe4-80bc-608c1fbed8bd.png)

From the reference site:
![image](https://user-images.githubusercontent.com/75774252/146358724-5792f9f3-ea2a-4fb5-8227-34a7698bc6bb.png)

**Comment by EktaNaik** [comment]
Fixed.
