### ISSUE TITLE
Single blog page: Sources section

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/tb_blog#15]
Description:
There is no **Sources** section on the reference site shared.

screenshot:
From the staging:https://truebasicsblog.wpengine.com/why-immunity-gets-affected-differently-across-demographics/ 

![image](https://user-images.githubusercontent.com/75774252/146365825-da780481-67fa-406d-8337-febda165f594.png)

Reference site: https://staging-healthtkart.kinsta.cloud/connect/10-nutrition-tips-for-kids/bid-9085/

![image](https://user-images.githubusercontent.com/75774252/146365945-1f4dee49-847d-4391-a3d9-42d45ff8e906.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency It's not a section, it's a part of blog content.
