### ISSUE TITLE
single blog page: only 1 article is getting displayed in what to read next section

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/tb_blog#16]
Description:
In the what to read next section only 1 article is getting displayed whereas in the reference site 6 articles are getting displayed

screenshot:
From the staging:
![image](https://user-images.githubusercontent.com/75774252/146366511-38e5152e-0787-445d-9168-889199113683.png)

From reference site:
![image](https://user-images.githubusercontent.com/75774252/146366552-859a745e-fa33-4b28-8efe-1363713b6a13.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency "what to read next" displays posts from a related category, & this category may not have 6 posts. 
_note : if there are multiple related categories it will fetch posts from the first related category_
