### ISSUE TITLE
Single blog post page: Recommended products section missing

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/tb_blog#17]
Description:
Recommended products section missing which should be above what to read next section as per the reference site is missing.

Screenshot:
Reference site:
![image](https://user-images.githubusercontent.com/75774252/146367081-c4dd734c-2cec-4f5c-bf85-ec042b20ec9e.png)

Staging site:
![image](https://user-images.githubusercontent.com/75774252/146367138-6637a927-cbd5-4447-892d-4e3dd5e3f146.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency  @EktaNaik  "recommended products" section was not mentioned in the TB blog project plan.
![image](https://user-images.githubusercontent.com/81617777/146528875-ca8e8677-ca2d-4bdc-9b59-801ff5509cab.png)
