### ISSUE TITLE
Category page: Breadcrumbs should only contain the Home and Post title

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/tb_blog#18]
Description:
Breadcrumbs should only contain the Home & Post title. At present, it is displaying category and sub-category.

Screenshot:
 reference:
![image](https://user-images.githubusercontent.com/75774252/146369372-b6fda646-c0d2-434c-93fb-bd6514fb068f.png)

staging:
![image](https://user-images.githubusercontent.com/75774252/146369460-af64e623-43df-43e4-bff8-7887e1b4f257.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency category page displays both the parent & child categories. refer this [link](https://staging-healthtkart.kinsta.cloud/connect/bodybuilding/bodybuilding-diet/)
_note: the category page you referred might be the parent category._
