### ISSUE TITLE
category page: The article tiles should not have borfer

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/tb_blog#20]
Description:
In the reference site, The article tiles do not have any border where as in the staging the tiles have border.

Screenshot:
The stageing
![image](https://user-images.githubusercontent.com/75774252/146370713-2eb91fc2-6720-4728-b086-7f814c5c4168.png)

The Reference:
![image](https://user-images.githubusercontent.com/75774252/146370832-e9d63172-6260-41de-9dab-4b9e104ee08b.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency New design has a border style for single post block/container
![image](https://user-images.githubusercontent.com/81617777/146552786-3e165906-c760-4997-b445-6eec10c38399.png)
