### ISSUE TITLE
Category page: Read this next section is missing

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/tb_blog#23]
Description:
Read these next section is missing at the end of the page.

Screenshot:
Reference site:
![image](https://user-images.githubusercontent.com/75774252/146372163-15fd49fc-da88-4df8-9c57-8ac3894b942d.png)

Staging site
![image](https://user-images.githubusercontent.com/75774252/146372250-55d9fdb0-632a-4b13-b005-f9d49b4d4f30.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency @EktaNaik "read these next" is not mentioned in the project plan [doc](https://docs.google.com/document/d/1m_QFvTZBUU5RxdG7wvHmuP0o1XCPR0TfGAk6oPQQOnQ/edit?usp=sharing)
![image](https://user-images.githubusercontent.com/81617777/146551905-5b3bc0d1-29a6-4a6f-941d-a576bd5415da.png)
