### ISSUE TITLE
Homepage- Firefox(mobile)- Explore articles: Text on the tabs is getting cropped

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/tb_blog#26]
Description:
 Text on the tabs under the explore articles section is getting cropped

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/146493214-fde1ebc8-a0f3-48ca-a8e8-9cd2a5edac0f.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency couldn't replicate the issue.
![image](https://user-images.githubusercontent.com/81617777/146551166-44a2a047-1572-48cb-b90a-2ad724f04915.png)
