### ISSUE TITLE
Header Menu- Firefox: The images added in the menu are getting cropped

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/tb_blog#6]
**Description:**
The images added in the header menu are getting cropped. 

**Screenshot:**
From the staging(the issue) :
![image](https://user-images.githubusercontent.com/75774252/146350254-84c5ddb8-17c5-4974-b914-8c9601e35961.png)

From Live:
![image](https://user-images.githubusercontent.com/75774252/146350522-eed594af-da10-4e2b-81c9-aba2a24db8dc.png)

**Comment by EktaNaik** [comment]
Fixed.
