### ISSUE TITLE
Footer- The titles of the footer widget are added as h3 tags 

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/tb_blog#8]
Description:
The titles of the footer widget are added as h3 tags whereas on https://www.truebasics.com/ they are added as h4 tags.

Screenshots:
From the staging:
![image](https://user-images.githubusercontent.com/75774252/146354461-951e3041-149d-4ca5-a00a-8f2006ff066b.png)

From live:
![image](https://user-images.githubusercontent.com/75774252/146354667-5602a006-8a4d-4bdf-aceb-32e6095b559c.png)

**Comment by EktaNaik** [comment]
Fixed.
